Refine build script

diff --git a/trunk/build_firmware b/trunk/build_firmware
--- a/trunk/build_firmware
+++ b/trunk/build_firmware
@@ -1,5 +1,15 @@
 #!/bin/sh
 
+[ -z "$1" ] && [ ! -z "$BOARD_NAME" ] && $0 $BOARD_NAME && exit 0
+[ -z "$1" ] && echo "Please run '$0 BOARD_NAME' to start build (see 'configs/templates/') " && exit 1
+
+if [ ! -f configs/templates/$1.config ] ; then
+	echo "configs/templates/$1.config not found "
+	exit 1
+fi
+
+cp -f configs/templates/$1.config .config
+
 ROOTDIR=`pwd`
 export ROOTDIR=$ROOTDIR
 
@@ -145,6 +155,25 @@ rm -rf "$dir_wifi_dst/mt7610"
 rm -rf "$dir_wifi_dst/mt76x2"
 rm -rf "$dir_wifi_dst/mt76x3"
 rm -rf "$dir_wifi_dst/mt7628"
+rm -rf "$dir_wifi_dst/mt7615"
+mkdir -p "$dir_wifi_dst/mt7615/embedded"
+cp -f "$dir_wifi_src/rtpci/4.4.2.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
+
+PATCH_DIR="${ROOTDIR}/PROMETHEUS/wifi_patch"
+if [ "$CONFIG_APPLY_PROMETHEUS_WIFI_DRIVER_PATCH" = "y" ] && [ ! -f "$dir_wifi_src/.patched_by_PROMETHEUS" ] ; then
+	for p in $(ls ${PATCH_DIR} |sort -n) ; do
+		echo "apply PROMETHEUS wifi patch: $p"
+		patch -p2 -i "${PATCH_DIR}/$p"
+	done
+	touch "$dir_wifi_src/.patched_by_PROMETHEUS"
+elif [ "$CONFIG_APPLY_PROMETHEUS_WIFI_DRIVER_PATCH" != "y" ] && [ -f "$dir_wifi_src/.patched_by_PROMETHEUS" ] ; then
+	for p in $(ls ${PATCH_DIR} |sort -rn) ; do
+		echo "revert PROMETHEUS wifi patch: $p"
+		patch -Rp2 -i "${PATCH_DIR}/$p"
+	done
+	rm -f "$dir_wifi_src/.patched_by_PROMETHEUS"
+fi
+
 if [ -n "$CONFIG_RT2860V2_AP" ] ; then
 	dir_wifi_ver="2.7.X.X"
 	if [ "$CONFIG_RALINK_RT3883" = "y" ] && [ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "2.4" ] ; then
@@ -212,6 +241,11 @@ if [ -n "$CONFIG_MT7628_AP" ] ; then
 	cp -rfL "$dir_wifi_src/rtsoc/$dir_wifi_ver/mt7628" "$dir_wifi_dst/"
 	cp -rfL "$dir_wifi_src/rtsoc/$dir_wifi_ver/mt7628_ap" "$dir_wifi_dst/"
 fi
+if [ -n "$CONFIG_MT7615_AP" ] ; then
+	dir_wifi_ver="4.4.2.1"
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615" "$dir_wifi_dst/"
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615_ap" "$dir_wifi_dst/"
+fi
 ############################ HWNAT ####################################
 dir_ppe_src="$ROOTDIR/proprietary/rt_ppe"
 dir_ppe_dst="$ROOTDIR/$CONFIG_LINUXDIR/net/nat"
@@ -276,36 +310,42 @@ if [ "$CONFIG_FIRMWARE_ENABLE_IPV6" != "y" ] ; then
 	func_enable_busybox_param "CONFIG_FEATURE_IP_LINK"
 	func_enable_busybox_param "CONFIG_FEATURE_IP_ROUTE"
 fi
+#SFE
+if [ "$CONFIG_FIRMWARE_INCLUDE_SFE" = "y" ] ; then
+	func_enable_kernel_param "CONFIG_SHORTCUT_FE"
+else
+	func_disable_kernel_param "CONFIG_SHORTCUT_FE"
+fi
 ############################# USB #####################################
 if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
-	func_disable_kernel_param "CONFIG_SWAP"
-	func_disable_kernel_param "CONFIG_FAT_FS"
-	func_disable_kernel_param "CONFIG_MSDOS_FS"
-	func_disable_kernel_param "CONFIG_VFAT_FS"
-	func_disable_kernel_param "CONFIG_UFSD_FS"
-	func_disable_kernel_param "CONFIG_EXFAT_FS"
-	func_disable_kernel_param "CONFIG_EXT2_FS"
-	func_disable_kernel_param "CONFIG_EXT3_FS"
-	func_disable_kernel_param "CONFIG_EXT4_FS"
-	func_disable_kernel_param "CONFIG_JBD"
-	func_disable_kernel_param "CONFIG_JBD2"
-	func_disable_kernel_param "CONFIG_XFS_FS"
-	func_disable_kernel_param "CONFIG_FUSE_FS"
-	func_disable_kernel_param "CONFIG_FSCACHE"
-	func_disable_kernel_param "CONFIG_INOTIFY_USER"
-	func_disable_kernel_param "CONFIG_NFSD"
-	func_disable_kernel_param "CONFIG_PARTITION_ADVANCED"
-	func_disable_kernel_param "CONFIG_NLS_CODEPAGE_866"
-	func_disable_kernel_param "CONFIG_NLS_ISO8859_1"
-	func_disable_kernel_param "CONFIG_SCSI"
-	func_disable_kernel_param "CONFIG_SCSI_MOD"
-	func_disable_kernel_param "CONFIG_INPUT"
-	func_disable_kernel_param "CONFIG_USB_SUPPORT"
-	func_disable_kernel_param "CONFIG_HID_SUPPORT"
-	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
-	func_disable_kernel_param "CONFIG_CRC16"
-	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
-	func_disable_kernel_param "CONFIG_RT3XXX_EHCI_OHCI"
+# 	func_disable_kernel_param "CONFIG_SWAP"
+# 	func_disable_kernel_param "CONFIG_FAT_FS"
+# 	func_disable_kernel_param "CONFIG_MSDOS_FS"
+# 	func_disable_kernel_param "CONFIG_VFAT_FS"
+# 	func_disable_kernel_param "CONFIG_UFSD_FS"
+# 	func_disable_kernel_param "CONFIG_EXFAT_FS"
+# 	func_disable_kernel_param "CONFIG_EXT2_FS"
+# 	func_disable_kernel_param "CONFIG_EXT3_FS"
+# 	func_disable_kernel_param "CONFIG_EXT4_FS"
+# 	func_disable_kernel_param "CONFIG_JBD"
+# 	func_disable_kernel_param "CONFIG_JBD2"
+# 	func_disable_kernel_param "CONFIG_XFS_FS"
+# 	func_disable_kernel_param "CONFIG_FUSE_FS"
+# 	func_disable_kernel_param "CONFIG_FSCACHE"
+# 	func_disable_kernel_param "CONFIG_INOTIFY_USER"
+# 	func_disable_kernel_param "CONFIG_NFSD"
+# 	func_disable_kernel_param "CONFIG_PARTITION_ADVANCED"
+# 	func_disable_kernel_param "CONFIG_NLS_CODEPAGE_866"
+# 	func_disable_kernel_param "CONFIG_NLS_ISO8859_1"
+# 	func_disable_kernel_param "CONFIG_SCSI"
+# 	func_disable_kernel_param "CONFIG_SCSI_MOD"
+# 	func_disable_kernel_param "CONFIG_INPUT"
+# 	func_disable_kernel_param "CONFIG_USB_SUPPORT"
+# 	func_disable_kernel_param "CONFIG_HID_SUPPORT"
+# 	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
+# 	func_disable_kernel_param "CONFIG_CRC16"
+# 	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
+# 	func_disable_kernel_param "CONFIG_RT3XXX_EHCI_OHCI"
 	func_disable_busybox_param "CONFIG_FDISK"
 	func_disable_busybox_param "CONFIG_FEATURE_FDISK_WRITABLE"
 	func_disable_busybox_param "CONFIG_FEATURE_FDISK_ADVANCED"
@@ -321,10 +361,10 @@ if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; th
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_EXT"
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_XFS"
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_LINUXSWAP"
-	if [ "$CONFIG_FIRMWARE_INCLUDE_OPENVPN" != "y" ] ; then
-		func_disable_kernel_param "CONFIG_TUN"
-		func_disable_kernel_param "CONFIG_HOTPLUG"
-	fi
+#	if [ "$CONFIG_FIRMWARE_INCLUDE_OPENVPN" != "y" ] ; then
+#		func_disable_kernel_param "CONFIG_TUN"
+#		func_disable_kernel_param "CONFIG_HOTPLUG"
+#	fi
 	CONFIG_FIRMWARE_INCLUDE_NFSD=n
 else
 ############################# UFSD ####################################
@@ -374,13 +414,13 @@ if [ "$CONFIG_FIRMWARE_ENABLE_SWAP" != "y" ] ; then
 	func_disable_busybox_param "CONFIG_SWAPONOFF"
 fi
 ############################# NFSD ####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_NFSD"
-fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" ] ; then
+#	func_disable_kernel_param "CONFIG_NFSD"
+# fi
 ############################# UVC #####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_UVC" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
-fi
+#if [ "$CONFIG_FIRMWARE_INCLUDE_UVC" != "y" ] ; then
+#	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
+#fi
 ############################# HID #####################################
 if [ "$CONFIG_FIRMWARE_INCLUDE_HID" != "y" ] ; then
 	func_disable_kernel_param "CONFIG_INPUT"
@@ -458,32 +498,36 @@ if [ "$CONFIG_FIRMWARE_INCLUDE_IFB" != "y" ] ; then
 	func_disable_kernel_param "CONFIG_IFB"
 fi
 ############################# NFSC ####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_FSCACHE"
-	func_disable_kernel_param "CONFIG_NFS_FS"
-fi
+#if [ "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" ] ; then
+#	func_disable_kernel_param "CONFIG_FSCACHE"
+#	func_disable_kernel_param "CONFIG_NFS_FS"
+#fi
 ############################# CIFS ####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_CIFS"
-	func_disable_busybox_param "CONFIG_FEATURE_MOUNT_CIFS"
-fi
-if [ "$CONFIG_FIRMWARE_INCLUDE_SMBD" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
-fi
-if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_NETWORK_FILESYSTEMS"
-	if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
-		func_disable_kernel_param "CONFIG_NLS"
-		func_disable_kernel_param "CONFIG_LBDAF"
-	fi
-fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
+# 	func_disable_kernel_param "CONFIG_CIFS"
+# 	func_disable_busybox_param "CONFIG_FEATURE_MOUNT_CIFS"
+# fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_SMBD" != "y" ] ; then
+# 	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
+# fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
+# 	func_disable_kernel_param "CONFIG_NETWORK_FILESYSTEMS"
+# 	if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
+# 		func_disable_kernel_param "CONFIG_NLS"
+# 		func_disable_kernel_param "CONFIG_LBDAF"
+# 	fi
+# fi
 ############################# USB AUDIO ###############################
-if [ "$CONFIG_FIRMWARE_INCLUDE_AUDIO" != "y" ] || [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
-	func_disable_kernel_param "CONFIG_FW_LOADER"
-	func_disable_kernel_param "CONFIG_SOUND"
-fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_AUDIO" != "y" ] || [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
+# 	func_disable_kernel_param "CONFIG_FW_LOADER"
+# 	func_disable_kernel_param "CONFIG_SOUND"
+# fi
 #######################################################################
+if [ "$CONFIG_WITHOUT_KERNEL" != "y" ] ; then
 echo --------------------------MAKE-DEP--------------------------------
 make dep
+fi
+if [ "$2" != "kmod" ] ; then
 echo --------------------------MAKE-ALL--------------------------------
 make
+fi
